### ISSUE TITLE
How to test the accuracy of multical and where is the multical.workspace and /path/to/calibration/workspace.ws ?

### ISSUE THREAD

**Issue by chaytonmin** [saulzar/multical#5]
How to test the accuracy of multical and where is the multical.workspace and /path/to/calibration/workspace.ws ?

**Comment by saulzar** [comment]
These are files which are outputs from the calibration e.g. they will be written to after the calibration process.

Check the README.md for most recent details as I have updated it for the most recent version. I have changed the name since the first release - It is 'calibration.pkl'  which gets written to the --output_path    (or by --image_path by default).

I have also written some FAQs for how to evaluate a calibration - let me know if you find this useful! Thanks

**Comment by chaytonmin** [comment]
> These are files which are outputs from the calibration e.g. they will be written to after the calibration process.
> 
> Check the README.md for most recent details as I have updated it for the most recent version. I have changed the name since the first release - It is 'calibration.pkl' which gets written to the --output_path (or by --image_path by default).
> 
> I have also written some FAQs for how to evaluate a calibration - let me know how you get on if this doesn't answer your question! Thanks

Awesome work! I will try it.
